## calcule texture for HC soils's DSSAT
# library(soiltexture)
library(tidyverse)
library(sf)
library(raster)
library(foreign)
library(rgdal)
library(spdplyr)
library(stringr)
library(rgeos)
library(broom)
library(maptools)
library(soiltexture)
library(data.table)



source('HC_generic_soil.R')


path_data <- 'data/'
path_soil <- paste0(path_data, 'Soil_HC/HC.SOL')
path_soil_csv <- paste0(path_data, 'Soil_HC/identificadores_ingles.csv')


HC_soil_df <- readHC_soil(path_soil)

class_spanish <- read_csv(path_soil_csv)

HC_texture <- inner_join(HC_soil_df, class_spanish, by = c("texture" = "English_key"))


HC_texture %>%
  group_by(name_key) %>%
  summarise(n())
## 

source('soil_functions.R')
path_data <- 'data/'

## Textura informacion CIAT
# library(velox)
raster_textura <- raster(paste0(path_data, 'Soil_Colombia/Clasificación textural/Clasificacion textural.tif'))  ## Clasificación de texturas
class_textura <- read.dbf(paste0(path_data, 'Soil_Colombia/Clasificación textural/Clasificacion textural.tif.vat.dbf'))

# raster_textura_vx <- velox(raster_textura)


class_textura <- class_textura %>%
  mutate(ClaseNum = 1:length(ClaseText))

## Shape Colombia SIGOT
shape_colombia <- readOGR(dsn = paste0(path_data, 'Shape_Colombia/Municipios_SIGOT_geo.shp'),
layer = 'Municipios_SIGOT_geo')
# shape_colombia <- st_read(dsn = paste0(path_data, 'Shape_Colombia/Municipios_SIGOT_geo.shp'),
#         layer = 'Municipios_SIGOT_geo')
# st_as_sf(shape_colombia)
## Cambiando la codificacion de las columnas necesarias

shape_colombia <- shape_colombia %>%
  mutate(NOM_MUNICI = iconv(NOM_MUNICI, 'UTF-8', 'latin1'), 
         NOMBRE_DPT = iconv(NOMBRE_DPT, 'UTF-8', 'latin1'))



## Rasta information (was generated by AEPS (Big Data CIAT))

rasta <- read_csv(paste0(path_data, 'Soil_Rasta/Rastas_3.csv'),cols(
  .default = col_character(),
  ID_LOTE = col_integer(),
  ID_FINCA = col_integer(),
  ID_RASTA = col_integer(),
  PENDIENTE = col_double(),
  NO_CAPAS = col_integer(),
  ESPESORES = col_character(),
  PH = col_double(),
  PROFUNDIDAD_CARBONATOS = col_integer(),
  HOR_PEDREG_ROCOSO_PROFUNDIDAD_RASTA = col_integer(),
  HOR_PEDREG_ROCOSO_ESPESOR_RASTA = col_integer(),
  PROFUND_PRIMERAS_ROCAS_PIEDRAS_RASTA = col_integer(),
  PROFUND_CAP_ENDURE_RASTA = col_integer(),
  ESPESOR_CAP_ENDURE_RASTA = col_double(),
  PROFUND_MOTEADOS_RASTA = col_integer(),
  PROFUND_RAICES_VIVAS_RASTA = col_integer()
), col_names = T) %>%
  mutate(ID_LOTE = as.character(ID_LOTE))

## Management Cordoba

management_cordoba <- read_csv(paste0(path_data, 'Soil_Rasta/Practicas_Cordoba.csv'))


identifier <- read_csv(paste0(path_data, 'Soil_Rasta/identificadores.csv'))

## sacar textura para Cordoba (joint entre rasta y el archivo de Practicas cordoba by ID_LOTE)  y solo el cultivo maiz

vars_ID <- management_cordoba %>%
  dplyr::select(ID_LOTE, MUNICIPIO, DEPARTAMENTO, TIPO_CULTIVO, LAT_LOTE, LONG_LOTE) %>%
  filter(!is.na(LONG_LOTE), !is.na(LAT_LOTE), TIPO_CULTIVO == 'Maiz') %>%
  mutate(lat = classify_coords(LAT_LOTE, long = F), long = classify_coords(LONG_LOTE))

soil_rasta_df <- inner_join(rasta, vars_ID, by = 'ID_LOTE')


## Departamentos a utilizar: Tolima, Cordoba, Valle, Casanare
# es importante poder mostrar en que lados de Colombia tenemos informacion acerca de la informacion de Rasta

zonas <- paste('TOLIMA', 'CÓRDOBA', 'VALLE', 'CASANARE', sep = '|')

soils_dpto <- shape_colombia %>%
  filter(str_detect(NOMBRE_DPT, zonas))

extent_region <- soils_dpto %>%
  extent()

text_dptos <- crop(raster_textura, extent_region)  ## textura Mayesi para la zona de estudio


# pasar al sistema de coordenadas planas


## sistema de coordenadas planas para colombia by Fabio Castro

sr <- '+proj=tmerc +lat_0=4.596200416666666 +lon_0=-74.07750791666666 +k=1 +x_0=1000000 +y_0=1000000 +ellps=GRS80 +towgs84=0,0,0,0,0,0,0 +units=m +no_defs'
soils_dpto <- spTransform(soils_dpto, sr)

# soils_dpto = st_transform(shape_colombia, sr) 
text_dptos <- raster::projectRaster(text_dptos, crs = sr)


# raster_textura_vx$crop(extent_region)

## Mostrar las texturas de rasta por lat y long
soil_rasta_vars <- soil_rasta_df %>%
  filter(TIPO_CULTIVO == 'Maiz') %>%
  dplyr::select(NO_CAPAS, PH, TEXTURAS, DEPARTAMENTO, MUNICIPIO, TIPO_CULTIVO, LAT_LOTE, LONG_LOTE, lat, long) %>%
  mutate(ID = 1:length(NO_CAPAS))

## arreglar un individuo por textura (plotear la textura de la primera profundidad)

tidy_rasta_soil <- soil_rasta_vars %>%
  mutate(TEXTURAS = strsplit(TEXTURAS, ",")) %>%
  unnest(TEXTURAS) %>% ## seleccionamos la textura de la primera profundidad
  group_by(ID) %>%
  filter(row_number() == 1) %>%
  ungroup()


tidy_rasta_soil <- inner_join(tidy_rasta_soil, identifier, by = c('TEXTURAS' = 'Spanish_key'))

coordinates(tidy_rasta_soil) <- c( "long", "lat")
tidy_rasta_soil = st_as_sf(tidy_rasta_soil)
st_crs(tidy_rasta_soil) <- 4326  ## coordenadas geograficas
tidy_rasta_soil <- st_transform(m.sf, sr)
tidy_rasta_soil <- as(tidy_rasta_soil, 'Spatial')

# tidy_rasta_soil <- sp::spTransform(tidy_rasta_soil,  CRS= sr) 

# rasta_soil_sp <- spTransform(tidy_rasta_soil, CRS(sr)) 


tidy_rasta_soil <- tidy_rasta_soil[soils_dpto, ]


tidy_rasta_soil_bf <- gBuffer(tidy_rasta_soil, width = 2000, byid = TRUE)
# tidy_rasta_soil_bf <- spTransform(tidy_rasta_soil_bf, CRS(sr)) 


## Extract points
# extract_by_polygon(1, r = text_dptos, shape = tidy_rasta_soil_bf)
library(foreach)
library(doSNOW) 

cl <- makeCluster(25)
registerDoSNOW(cl)  ## For Windows

to_ <- 1:dim(tidy_rasta_soil_bf)[1]

values <- foreach(i = to_, .packages = c('raster', 'dplyr', 'rgdal', 'foreach')) %dopar% {
  
  extract_by_polygon(i, r = text_dptos, shape = tidy_rasta_soil_bf)
  
}

values <- values %>%
  bind_rows()

values <- values %>%
  mutate(values = as.integer(values))

values_text <- inner_join(values, class_textura,  by = c("values" = "ClaseNum"))

stopCluster(cl) 
 
tidy_rasta_soil_df <- tidy_rasta_soil_bf %>%
  as_data_frame()

soils_rasta_text <- inner_join(tidy_rasta_soil_df, values_text, by = c('MUNICIPIO'  = 'NOM_MUNICI'))

soils_rasta_text <- soils_rasta_text %>%
  nest(-MUNICIPIO, -DEPARTAMENTO)


## top texturas by mun
top_text <- soils_rasta_text  %>%
  mutate(mode_ = map(data, mode_df, 'ClaseText', 3)) %>%
  unnest(mode_)

soils_dpto_Sptext <- inner_join(tidy_rasta_soil_bf, top_text, by = 'MUNICIPIO', copy = TRUE) %>%
  as_data_frame()


## grafico by mun de estudio y cual seria el suelo de DSSAT
# soils_dpto_Sptext
# HC_texture
soils_dpto_Sptext <- inner_join(soils_dpto_Sptext, HC_texture, by = c("name" = "Spanish_texture")) %>%
  filter(complete.cases(MUNICIPIO))


# filtrar para los municipios de estudio

mun_usaid <- c('YOPAL', 'LORICA', 'IBAGUÉ', 'LA UNIÓN', 'ESPINAL', 'CERETÉ')
mun_usaid <- paste(mun_usaid, collapse = '|')
mun_usaid_text <- filter(top_text, str_detect(MUNICIPIO, mun_usaid))

# filter(soils_dpto_text, str_detect(NOMBRE_DPT, 'VALLE')) %>%
#   dplyr::select(NOM_MUNICI) %>%
#   magrittr::extract2(1)

library(forcats)
mun_usaid_text <- mun_usaid_text %>%
  mutate(top_textura = fct_reorder(factor(n), n, .desc = FALSE), 
         MUNICIPIO = fct_reorder(MUNICIPIO, n, .desc = FALSE))

mun_usaid_text <- inner_join(mun_usaid_text, HC_texture, by = c("ClaseText" = "Spanish_texture")) 

mun_usaid_text %>%
  dplyr::select(DEPARTAMENTO, MUNICIPIO, ClaseText, HC) %>%
  rename(Texture_MAYESI = ClaseText) %>%
  write.csv('soils_dssat_by_region.csv')

library(ggrepel)
ggplot(mun_usaid_text, aes(MUNICIPIO, top_textura, fill = ClaseText)) +
  geom_bar(stat="identity", position=position_dodge()) +
  scale_fill_manual(values = c("#8c510a",
                               "#bf812d",
                               "#c7eae5",
                               "#80cdc1",
                               "#35978f",
                               "#01665e",
                               "#003c30"), name= "Textura") +
  geom_text(aes(MUNICIPIO, top_textura, label = ClaseText), 
            position = position_dodge(0.99),
            vjust= - 1) +
  
  geom_label_repel(data = mun_usaid_text,
                   aes(label = HC, x = MUNICIPIO, y = top_textura),
                   fontface = 'bold',
                   box.padding = unit(0.35, "lines"),
                   point.padding = unit(0.5, "lines"),
                   segment.color = 'black'
                   
  )



## plot rasta (puntos de maiz para Colombia)



## Mostrar las texturas de rasta por lat y long
soil_rasta_vars <- soil_rasta_df %>%
  filter(TIPO_CULTIVO == 'Maiz') %>%
  dplyr::select(NO_CAPAS, PH, TEXTURAS, DEPARTAMENTO, MUNICIPIO, TIPO_CULTIVO, LAT_LOTE, LONG_LOTE, lat, long) %>%
  mutate(ID = 1:length(NO_CAPAS))

## arreglar un individuo por textura (plotear la textura de la primera profundidad)

tidy_rasta_soil <- soil_rasta_vars %>%
  mutate(TEXTURAS = strsplit(TEXTURAS, ",")) %>%
  unnest(TEXTURAS) %>% ## seleccionamos la textura de la primera profundidad
  group_by(ID) %>%
  filter(row_number() == 1) %>%
  ungroup()


tidy_rasta_soil <- inner_join(tidy_rasta_soil, identifier, by = c('TEXTURAS' = 'Spanish_key'))
# text_dptos
# tidy_rasta_soil <- tidy_rasta_soil %>%
  # filter(DEPARTAMENTO == 'TOLIMA')
coordinates(tidy_rasta_soil) <- c( "long", "lat")
sr <- '+proj=tmerc +lat_0=4.596200416666666 +lon_0=-74.07750791666666 +k=1 +x_0=1000000 +y_0=1000000 +ellps=GRS80 +towgs84=0,0,0,0,0,0,0 +units=m +no_defs '
proj4string(tidy_rasta_soil) <- CRS(sr)

rasta_soil_sp <- spTransform(tidy_rasta_soil, CRS(sr)) 
# proj4string(soils_dpto) <- CRS(sr)
# soils_dpto <- spTransform(soils_dpto, CRS(sr))

rasta_soil_sp <- rasta_soil_sp[soils_dpto, ]
# plot(soils_dpto)
# plot(rasta_soil_sp, add = T, col = 'red')
# plot(rasta_soil_sp[soils_dpto, ], add = T, col = 'blue')
## buffer


rasta_bf_2km <- gBuffer(rasta_soil_sp, width=0.01800018, byid = T)

extract(text_dptos, rasta_bf_2km)
text_dptos <- raster::projectRaster(text_dptos, crs = sr)
proof <- extract(text_dptos, rasta_bf_2km)
# 
# plot(soils_dpto)
# plot(pc, add = T, col = 'blue')
# 
# pc <- pc %>%
#   filter(str_detect(DEPARTAMENTO, zonas))
# 
# text_dptos
# soils_dpto2 <- soils_dpto %>%
#   filter(NOMBRE_DPT == 'TOLIMA')
# plot(soils_dpto2)
# mask(pc, soils_dpto)
# plot(pc, add = T)
# plot(pc[soils_dpto, ], add = T, col = 'red')
